elegent_entropy:
  repeat: 1 # For random seed

  motion_adapter: guoyww/animatediff-motion-adapter-v1-5-2

  sd_model: runwayml/stable-diffusion-v1-5

  checkpoint: models/Checkpoint/elegantEntropy_v14.safetensors

  lora:
    - models/LoRA/Elixir.safetensors
    - models/LoRA/howlbgsv3.safetensors
    - models/LoRA/Ghibli_v6.safetensors

  textual_inversion:
    - models/Textual_Inversion/verybadimagenegative_v1.3.pt

  use_lcm: True
  lcm_path: models/LoRA/pytorch_lora_weights.safetensors

  seed: 
    - -1

  steps: 
    - 8

  guidance_scale:
    - 8

  prompt:
    - extremely intricate, setting sun, close-up, ultra-detailed, Artificial intelligence marketplace, best quality, imagination, rough skin, best lighting, cottagebore, professional majestic oil painting by Ed Blinkey, rim light, Vast grassland
    - wearing viking armor, (hyper-detailed, masterpiece), best quality, high quality, ((ivy-covered house)), mighty oak, random beautiful jungle, highly detailed, (art by Donato Giancola:1.0)
    - best quality, highres, vibrant green tinted colors, water
    - High Detail, scientific discoveries, magical, (Panorama:0.6), detailed colors, grass, iridescent pond, red sun shines hot, shabby, ink strokes, realistic lighting, (flowers:1.3) on balustrade and (plants:1.3) on terrace floor, rough skin, architectural streets, masterpiece
    - by Jeremy Mann, professional (landscape painting) of natures, impression, ultra-HD, tranquil, (cyberpunk), warm, beautiful, grass
    - art by Midjourney and Greg Rutkowski, particles, (pixel_art), tree, 1girl's side face blends into it, ((island sanctuary)), magical nocturnal flora and fauna, mini\(ttp\, best quality), highly detailed, 4k textures, (best quality:1.4)
    - fine art, ((masterpiece)), wide color coverage, architecture, photorealistic, solo, ancient greek god, Cinematic Lighting, trending on CGSociety, sunset, isometric view, elegant, day, flowers, beautiful, magic, high contrast, mountain, (realistic)
    - cloudy sky, photo-realistic, cinematic lighting, professional majestic oil painting by Ed Blinkey, outdoors, fantasy, waterfall, snow, color
    - Elixir, modelshoot style, acrylic on canvas, 4k textures, (by shawn coss), with a network of subterranean tunnels carved by ancient inhabitants., landscape, a harbor, soft focus, best quality, (hilltop|Snow cover:0.7), photorealistic painting art

  n_prompt:
    - watermark, signature, poorly drawn face, worst quality, mutated, Low_picture_anime, extra limbs, glans, lowres, mutation hands, normal quality, cropped, windows, Abnormal hands, close up, thin lines, 3d, greyscale, worst quality, verybadimagenegative_v1.3, acnes, mutilated, malformed hands
    - signature, error, lowres, ((close up)), mutated hands, (deformed), bad anatomy, looking away, huge eyes, (low quality), nfixer, watermark, worst quality, disfigured, letterbox, (((mutation))), extra legs, duplicate, paintings, sketches, bad hands, extra limbs, deleted, child:1.1, extra digit, tiling, mutation fingers, By bad artist, (worst quality:1.3), dull, 3D face, logo
    - watermark, signature, b&w, geometry, low-res, disgusting
    - watermark, signature, ugly, extra arms, neon, cartoon, title, muscular, ((bad anatomy)), nfixer, anime, mutated, tiling, duplicate, DeepNegative, disfigured, (normal quality), skin spots, ((monochrome)), cartoons
    - signature, [out of frame], (worst quality), watermark, badhandv4, (bokeh), verybadimagenegative_v1.3, bad anatomy, sketches, text, (fused fingers, (missing legs), worst quality:2), futuristic, paintings, polar lowres, extra fingers, ugly, illustration, (rib:1.0), character name, ((disfigured, (extra arms))), logo, type, sketch, blurry, ((missing arms), blurry:2.0), 3d, censored, bad-picture-chill-75v, people, artist name, By bad artist, cloned face, jpeg artifacts, [BadDream], ((deformed)), low quality, malformed limbs, long neck, poorly drawn face, 3d render, error, EasyNegativeV2, normal quality, (too many fingers), poorly drawn hands, (((bad proportions), close up)), old, (By bad artist anime:0.7, less fingers:1.1), cartoon, water mark, grayscale, mountains
    - watermark, signature, (((disfigured))), blurry, bad proportions, (distorted), mutated hands, crowded, ((missing arms)), acnes, bad_prompt, ((extra limbs)), paintings, Photoshop, worstquality, (mutated hands and fingers:1.4), extra fingers, (bad anatomy, :1.3, worst quality), cartoon, 3d, anime
    - watermark, signature, blurry, (nipple:1.4), brandnameimitation, Reference sheet, mutated, extra limbs, (disfigured:1.3), amputation, EasyNegativeV2, extra arms, (low quality), Missing Legs, (worst quality:2)
    - By bad artist, fewer fingers, nsfw, drawing, (EasyNegativeV2:1.0), signature, (low quality, fused fingers), text, mutation, (distorted), person, (lipstick), hazy, deformed, girl, badhandv4, extra limbs, (worst quality:1.2), poorly drawn face, bad art, watermark, EasyNegativeV2
    - watermark, signature, disfigured, cartoons, poorly drawn hands, (render, bad hands, (deformed)), normal quality, logo, text, (low quality:1.4), low-res, bad feet, (missing fingers), black-white, cartoon, blurry, bad composition, low quality, disgusting